export const FETCH_MAIN_PRODUCT_CATEGORY = 'FETCH_MAIN_PRODUCT_CATEGORY';
export const FETCH_MAIN_PRODUCT_CATEGORY_SUCCESS = 'FETCH_MAIN_PRODUCT_CATEGORY_SUCCESS';
export const SET_TOGGLE_MODAL = 'SET_TOGGLE_MODAL';
